server:
  port: ${PORT:8091}
  servlet:
    context-path: /product-service/api
spring:
  application:
    name: product-service
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      auto-index-creation: true