version: "3"
services:
  user-service-db:
    image: postgres
    container_name: user-service-db-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user-service
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - my-network
  order-service-db:
    image: postgres
    container_name: order-service-db-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order-service
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - my-network
  product-db:
    image: mongo
    container_name: product-db-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=product-service
      - MONGO_DB_USERNAME=username
      - MONGO_DB_PASSWORD=password
    volumes:
      - product-data:/data/db/
    #      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
    #      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    networks:
      my-network:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@product-db:27017/
      - ME_CONFIG_BASICAUTH=false
    networks:
      my-network:
  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://user-service-db:5432/user-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILE_ACTIVE=dev
      - PORT=8092
#    restart: always
    ports:
      - "8092:8092"
    networks:
      - my-network
    depends_on:
      - user-service-db
  product-service:
    image: product-service:latest
    container_name: product-service
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - PORT=8091
      - SPRING_DATA_MONGODB_HOST=product-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_DATA_MONGODB_DATABASE=product-service
#    restart: always
    ports:
      - "8091:8091"
    networks:
      - my-network
    depends_on:
      - product-db
  order-service:
    image: order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - PORT=8093
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-service-db:5432/order-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - PRODUCT_SERVICE_URL=http://product-service:8091/product-service/api/v1
      - USER_SERVICE_URL=http://user-service:8092/user-service/api/v1
#    restart: always
    ports:
      - "8093:8093"
    networks:
      - my-network
    depends_on:
      - order-service-db
volumes:
  user-data:
  order-data:
  product-data:
networks:
  my-network:
