version: "3"
services:
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    image: product-service:latest
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - PORT=8091
      - SPRING_DATA_MONGODB_HOST=product-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_DATA_MONGODB_DATABASE=product-service
    restart: always
    ports:
      - "8091:8091"
    networks:
      - my-network
    depends_on:
      - product-db
  product-db:
    image: mongo
    container_name: product-db-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=product-service
      - MONGO_DB_USERNAME=username
      - MONGO_DB_PASSWORD=password
    volumes:
      - db-data:/data/db/
#      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
#      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    networks:
      my-network:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@product-db:27017/
      - ME_CONFIG_BASICAUTH=false
    networks:
      my-network:
volumes:
  db-data:
networks:
  my-network: