apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-container
        image: lethanhsang14082001/user-service:latest
        ports:
        - name: "user-port"
          containerPort: 8092
        envFrom:
        - configMapRef:
            name: user-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - port: 8092
      targetPort: 8092
  type: LoadBalancer
