apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnvailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-container
        image: lethanhsang14082001/user-service:latest
        imagePullPolicy: IfNotPresent # Alway, IfNotPresent, Never
        ports:
        - name: "user-port"
          containerPort: 8092
        envFrom:
        - configMapRef:
            name: user-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - port: 8092
      targetPort: 8092
  type: LoadBalancer
