product:
  service:
    url: http://localhost:8091/
user:
  service:
    url: http://localhost:8092/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update