apiVersion: v1
kind: ConfigMap
metadata:
  name: product-db-config
data:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  MONGO_INITDB_DATABASE: "product-service"
  MONGO_DB_USERNAME: "username"
  MONGO_DB_PASSWORD: "password"
