apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  selector:
    matchLabels:
      app: product-app
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnvailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-container
        image: lethanhsang14082001/product-service:latest
        imagePullPolicy: IfNotPresent # Alway, IfNotPresent, Never
        ports:
        - name: "product-port"
          containerPort: 8091
        envFrom:
        - configMapRef:
            name: product-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-app
  ports:
    - port: 8091
      targetPort: 8091
  type: LoadBalancer
