apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  selector:
    matchLabels:
      app: order-app
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnvailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-container
        image: lethanhsang14082001/order-service:latest
        imagePullPolicy: IfNotPresent # Alway, IfNotPresent, Never
        ports:
        - name: "order-port"
          containerPort: 8093
        envFrom:
        - configMapRef:
            name: order-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-app
  ports:
    - port: 8093
      targetPort: 8093
  type: LoadBalancer
