version: "3"
services:
  user-db:
    image: postgres
    container_name: users-db-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user-service
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service:latest
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://user-db:5432/user-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILE_ACTIVE=dev
      - PORT=8092
    restart: always
    ports:
      - "8092:8092"
    networks:
      - my-network
    depends_on:
      - user-db
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_user
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#      - ./docker-volume/pgadmin:/var/lib/pgadmin
#    ports:
#      - 9000:80
volumes:
  db-data:
networks:
  my-network: